import { cp, mkdir, mkdtemp, readFile, readdir, realpath, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

// Usage: npm run sync:motions
// Builds every Motion Lab frame the website shows into ONE motion bundle at
// public/motions/: one copy of React and one Rive runtime shared by all of them, with
// each motion in its own chunk that loads only when the page mounts it. The website
// mounts motions straight into the page (src/components/MotionPreview.tsx), inside a
// shadow root so its CSS can't reach them, instead of one iframe (and one React and
// Rive per motion) each.
//
// Built with Motion Lab's own Vite, React 18 and Rive, so the motions run on the
// versions they were made with. A motion's id is `<project>/<slug>`, e.g. bifrost/01.
const motions = {
  bifrost: { content: 'bifrost-content', slugs: ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', 'cover'] },
  beam: { content: 'beam-content', slugs: ['cover'] },
};

const here = dirname(fileURLToPath(import.meta.url));
const website = resolve(here, '../..');
const motionLab = resolve(website, '..', 'Motion Lab');
const modules = join(motionLab, 'node_modules');
const output = join(website, 'public/motions');

// Reads one frame's entry from frames.ts. Each entry is a one-line object literal,
// so a few patterns are enough; fail loudly if its shape changes. Numbered frames are
// matched by `number`, unnumbered ones such as the cover by `slug`.
async function readFrame(content, project, slug) {
  const marker = /^\d+$/.test(slug) ? `{ number: ${Number(slug)},` : `slug: '${slug}'`;
  const frames = await readFile(join(content, 'frames.ts'), 'utf8');
  const line = frames.split('\n').find(frame => frame.includes(marker));
  if (!line) throw new Error(`${project} motion ${slug} is missing from frames.ts.`);
  const size = /width: ([\d.]+), height: ([\d.]+)/.exec(line);
  const background = /background: '([^']+)'/.exec(line);
  const box = /content: \{ x: ([\d.]+), y: ([\d.]+), width: ([\d.]+), height: ([\d.]+) \}/.exec(line);
  if (!size || !background || !box) throw new Error(`Could not read ${project} motion ${slug} from frames.ts.`);
  const imageName = /image: (\w+)/.exec(line)?.[1];
  const imagePath = imageName && new RegExp(`import ${imageName} from '(\\./[^']+)'`).exec(frames)?.[1];
  if (imageName && !imagePath) throw new Error(`Could not find the ${imageName} import in frames.ts.`);
  const [x, y, width, height] = box.slice(1).map(Number);
  return {
    width: Number(size[1]),
    height: Number(size[2]),
    background: background[1],
    image: imagePath ? join(content, imagePath) : undefined,
    content: { x, y, width, height },
    steps: Number(/\bsteps: (\d+)/.exec(line)?.[1]) || undefined,
  };
}

// Playback settings as Motion Lab's BifrostWorkspace reads them (defaults + settings.json).
async function readSettings(content, slug) {
  const defaults = { playbackRate: 1, holdSeconds: 2, slideSeconds: 1.2 };
  try {
    return { ...defaults, ...JSON.parse(await readFile(join(content, `motion-${slug}/settings.json`), 'utf8')) };
  } catch (error) {
    if (error.code === 'ENOENT') return defaults;
    throw error;
  }
}

// The bundle's entry, generated because it lists every motion. Plain JS with
// createElement: Motion Lab's tsconfig JSX setting doesn't reach this folder.
function entrySource(list) {
  const imports = list.map((motion, index) => motion.frame.image ? `import image${index} from ${JSON.stringify(motion.frame.image)};` : '').join('\n');
  const table = list.map((motion, index) => `  ${JSON.stringify(motion.id)}: {
    load: () => import(${JSON.stringify(motion.source)}),
    frame: ${JSON.stringify({ ...motion.frame, image: undefined })},
    image: ${motion.frame.image ? `image${index}` : 'undefined'},
    settings: ${JSON.stringify(motion.settings)},
  },`).join('\n');
  return `// Generated by scripts/motion-export/pack.mjs. Do not edit.
import { createElement, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { RuntimeLoader } from '@rive-app/react-canvas';
import { buildTimeline, positionAt } from ${JSON.stringify(join(here, 'timeline.js'))};
${imports}

// One Rive runtime for every motion, in this folder (not the unpkg CDN). Absolute
// paths: this code ends up in a shared chunk under chunks/, so a path relative to it
// would point there. The website serves the bundle at /motions/.
RuntimeLoader.setWasmUrl('/motions/rive.wasm');

const motions = {
${table}
};

/** The motions' own styles, linked inside each shadow root that shows one. */
export const stylesheet = '/motions/motions.css';

// Fonts must be declared on the document: @font-face inside a shadow root is ignored.
let fontsLinked = false;
function linkFonts() {
  if (fontsLinked) return;
  fontsLinked = true;
  const link = document.createElement('link');
  link.rel = 'stylesheet';
  link.href = '/motions/fonts.css';
  document.head.append(link);
}

/** Starts loading the Rive runtime ahead of the first motion that needs it. */
export function warm() {
  linkFonts();
  return RuntimeLoader.awaitInstance().catch(() => {});
}

// Timeline motions get a looping \`position\`, as Motion Lab's timeline dock drives it.
function usePosition(timeline) {
  const [position, setPosition] = useState(timeline ? timeline.from : 0);
  useEffect(() => {
    if (!timeline) return undefined;
    const start = performance.now();
    let request = requestAnimationFrame(function tick(now) {
      setPosition(positionAt(timeline, (now - start) / 1000));
      request = requestAnimationFrame(tick);
    });
    return () => cancelAnimationFrame(request);
  }, [timeline]);
  return position;
}

// Draws the frame the way Motion Lab's BifrostWorkspace does (frame image, then the
// motion in its content box) at the frame's Figma size, without the "Motion N" label.
function Frame({ Motion, entry, timeline }) {
  const position = usePosition(timeline);
  const { frame, image, settings } = entry;
  const box = frame.content;
  return createElement('div', { style: { position: 'absolute', left: 0, top: 0, width: frame.width, height: frame.height, overflow: 'hidden', background: frame.background } },
    image && createElement('img', { src: image, alt: '', style: { position: 'absolute', inset: 0, display: 'block', width: '100%', height: '100%' } }),
    createElement('div', { style: { position: 'absolute', left: box.x, top: box.y, width: box.width, height: box.height } },
      createElement(Motion, { position, values: settings.values ?? {} })));
}

/**
 * Mounts one motion into \`container\` (the page gives it the frame's size). \`ready\`
 * resolves once it has rendered; \`unmount\` stops it and frees everything it holds.
 */
export function mount(container, id) {
  const entry = motions[id];
  if (!entry) throw new Error(\`Unknown motion: \${id}\`);
  linkFonts();
  const root = createRoot(container);
  const timeline = entry.frame.steps ? buildTimeline(entry.settings, entry.frame.steps) : null;
  let unmounted = false;
  const ready = entry.load().then(module => {
    if (unmounted) return;
    root.render(createElement(Frame, { Motion: module.default, entry, timeline }));
    // React renders on the next task; resolve once the frame is in the container.
    return new Promise(resolve => {
      const check = () => (unmounted || container.firstChild ? resolve() : setTimeout(check, 8));
      check();
    });
  });
  return {
    ready,
    unmount() {
      unmounted = true;
      root.unmount();
    },
  };
}
`;
}

// realpath: macOS tmpdir is a symlink, which breaks Vite's output paths.
const work = await realpath(await mkdtemp(join(tmpdir(), 'motion-bundle-')));
const exportDir = join(work, 'out');

try {
  const list = [];
  for (const [project, { content: folder, slugs }] of Object.entries(motions)) {
    const content = join(motionLab, 'src/motion-lab', folder);
    for (const slug of slugs) {
      list.push({
        id: `${project}/${slug}`,
        source: join(content, `motion-${slug}/motion-${slug}.tsx`),
        frame: await readFrame(content, project, slug),
        settings: await readSettings(content, slug),
      });
    }
  }
  await writeFile(join(work, 'motions.js'), entrySource(list));

  const { build } = await import(pathToFileURL(join(modules, 'vite/dist/node/index.js')).href);
  await build({
    configFile: false,
    root: work,
    base: './',
    publicDir: false,
    logLevel: 'warn',
    resolve: {
      alias: {
        react: join(modules, 'react'),
        'react-dom': join(modules, 'react-dom'),
        '@rive-app/react-canvas': join(modules, '@rive-app/react-canvas'),
      },
    },
    build: {
      outDir: exportDir,
      emptyOutDir: true,
      // One stylesheet for every motion, linked into each shadow root by the page:
      // Vite's per-chunk CSS would be injected into the document head, where shadow
      // roots can't see it.
      cssCodeSplit: false,
      modulePreload: false,
      rollupOptions: {
        input: join(work, 'motions.js'),
        preserveEntrySignatures: 'strict',
        output: {
          entryFileNames: 'motions.js',
          chunkFileNames: 'chunks/[name]-[hash].js',
          assetFileNames: asset => (asset.names?.[0] ?? asset.name ?? '').endsWith('.css') ? 'motions.css' : 'assets/[name]-[hash][extname]',
        },
      },
    },
  });

  // Motion Lab serves /rive and /fonts from its public folder. Copy what the bundle
  // references and point those paths at /motions/ on the website.
  const publicReference = /(["'(])\/((?:rive|fonts)\/[\w.@-]+)/g;
  const copied = new Set();
  const fontFaces = new Set();
  const files = [join(exportDir, 'motions.js'), join(exportDir, 'motions.css'), ...(await readdir(join(exportDir, 'chunks'))).map(file => join(exportDir, 'chunks', file))];
  for (const path of files) {
    const code = (await readFile(path, 'utf8')).replace(publicReference, (match, quote, asset) => {
      copied.add(asset);
      return `${quote}/motions/${asset}`;
    });
    await writeFile(path, code);
    // @font-face from the motions' CSS and inline <style> tags, hoisted to the document.
    for (const [face] of code.matchAll(/@font-face\s*\{[^}]*\}/g)) fontFaces.add(face);
  }
  for (const asset of copied) {
    await mkdir(dirname(join(exportDir, asset)), { recursive: true });
    await cp(join(motionLab, 'public', asset), join(exportDir, asset));
  }
  await writeFile(join(exportDir, 'fonts.css'), `${[...fontFaces].join('\n')}\n`);
  await cp(join(modules, '@rive-app/canvas/rive.wasm'), join(exportDir, 'rive.wasm'));

  await rm(output, { recursive: true, force: true });
  await cp(exportDir, output, { recursive: true });
  console.log(`${list.length} motions bundled into public/motions/ (${[...copied].length} public assets, ${fontFaces.size} font faces).`);
} finally {
  await rm(work, { recursive: true, force: true });
}
